simulate_pedestrians:
  ros__parameters:
    rate: 30.0              # Higher update rate for smoother forces
    n_static_peds: 0
    n_moving_peds: 80       
    world_width: 10.0
    world_height: 10.0
    personal_space: 1.5     # Increased from 1.2 for earlier repulsion activation
    max_speed: 1.3          # Reduced max speed for better control
    respawn_time: 5.0
    n_peds: 25
    personal_space_radius: 1.0
    repulsion_gain: 15.0    # Increased from 10.0 for stronger short-range response
    collision_buffer: 0.3   # Keep physical collision threshold
    obstacle_gain: 5.0
    obstacle_range: 2.0
    start_x_range: [0.5, 2.0]
    end_x_range: [8.0, 10.0]
    y_range: [-4.0, 4.0]
    speed_range: [0.5, 1.2]
    n_trees: 0
    wait_time: 10.0         # Time between trips
    triangle:
      A: {x: 7.13649, y: -3.96949}
      B: {x: 6.97596, y: 2.96581}
      C: {x: 2.98578, y: 0.0501903}
    collision_gain: 12.0     # Strong repulsion force
    path_variation: 0.7      # Maximum variation in destination position

shibuya_crossing:
  ros__parameters:
    rate: 20.0              # Smooth animation rate
    n_peds: 80              # Dense crowd size
    personal_space: 2.0     # Maintain comfortable spacing
    max_speed: 1.3          # Slightly reduced from 1.4
    wait_time: 10.0         # Traffic light cycle

