simulate_pedestrians:
  ros__parameters:
    rate: 15.0
    n_static_peds: 100  # Increased density
    n_moving_peds: 20   # More dynamic crowd members
    world_width: 10.0
    world_height: 5.0
    personal_space: 1.0 # Increased from 0.8
    max_speed: 1.2      # Typical walking speed
    n_peds: 25
    personal_space_radius: 1.0
    repulsion_gain: 5.0
    obstacle_gain: 5.0
    obstacle_range: 2.0
    start_x_range: [0.5, 2.0]
    end_x_range: [8.0, 10.0]
    y_range: [-4.0, 4.0]
    speed_range: [0.5, 1.2]
    static_peds/x: [ 
      2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5,
      2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5,
      # ... (repeat 3 more times)
    ]
    static_peds/y: [
      1.5, 1.2, 0.9, 0.6, 0.3, 0.0, -0.3, -0.6,
      1.5, 1.2, 0.9, 0.6, 0.3, 0.0, -0.3, -0.6,
      # ... (repeat 3 more times)
    ]
    n_trees: 0
    tower:
      x: 5.0
      y: 0.0
      radius: 1.5
      height: 4.0

